### ISSUE TITLE
Updates to logs

### ISSUE THREAD

**Issue by rdesmond** [CodingNomads/mentor-portal#19]
* all logs need to be editable by the person who wrote them or admin - mentors can't adjust other mentors logs
* the date of the log should be automatic populated to today's date but adjustable 
* "Mentor" can be removed and that field is auto-populated in the DB by the logged in user - whoever is filling this log
* remove "Duration" - hide it from the front-end - no need to remove from application - may use it later
* sort logs by date and display newest first

**Comment by swford89** [comment]
All updates in `post-deployment-update-3` branch.
