### ISSUE TITLE
student count on mentor list page is always zero

### ISSUE THREAD

**Issue by rdesmond** [CodingNomads/mentor-portal#27]
On the Mentor List page, the "Student Count" shows zero (current students) for all mentors. For instance, it says the Gilad has "0/8 students" but he has several active students. We want this to show the number of "Active" students a mentor is currently assigned to, as well as the total number of students they're able to work with. So for Gilad that would show, for instance, "4/8 Students". If he had 4 active students and a total capacity to work with 8 students.

**Comment by swford89** [comment]
resolved with `post-deployment-update-5`
