### ISSUE TITLE
Assigned Students for a Mentor should only show "Active" students

### ISSUE THREAD

**Issue by rdesmond** [CodingNomads/mentor-portal#30]
Assigned Students under a given mentor should only show active students - and the student count for mentors should only include active students. For instance, under Gilad's "Assigned Students" it shows Fernanda who completed her program. She should not be included in that list. We only want to show Active students in the mentors "Assigned Students" tab.

**Comment by swford89** [comment]
resolved with `post-deployment-update-5`
